import type { ApolloPerson } from "./apollo-client.js";
import type { ApolloPeopleEnrichment } from "../db/schema.js";

/**
 * Transform an Apollo API person to our camelCase API response format.
 * Used by POST /search and POST /enrich responses.
 */
export function transformApolloPerson(person: ApolloPerson) {
  const org = person.organization;
  return {
    id: person.id,
    firstName: person.first_name,
    lastName: person.last_name,
    email: person.email ?? null,
    emailStatus: person.email_status ?? null,
    title: person.title,
    linkedinUrl: person.linkedin_url,
    // Person profile
    photoUrl: person.photo_url,
    headline: person.headline,
    city: person.city,
    state: person.state,
    country: person.country,
    seniority: person.seniority,
    departments: person.departments,
    subdepartments: person.subdepartments,
    functions: person.functions,
    twitterUrl: person.twitter_url,
    githubUrl: person.github_url,
    facebookUrl: person.facebook_url,
    employmentHistory: person.employment_history?.map((eh) => ({
      title: eh.title,
      organizationName: eh.organization_name,
      startDate: eh.start_date,
      endDate: eh.end_date,
      description: eh.description,
      current: eh.current,
    })),
    // Organization
    organizationName: org?.name,
    organizationDomain: org?.primary_domain,
    organizationIndustry: org?.industry,
    organizationSize: org?.estimated_num_employees?.toString(),
    organizationRevenueUsd: org?.annual_revenue?.toString(),
    organizationWebsiteUrl: org?.website_url,
    organizationLogoUrl: org?.logo_url,
    organizationShortDescription: org?.short_description,
    organizationSeoDescription: org?.seo_description,
    organizationLinkedinUrl: org?.linkedin_url,
    organizationTwitterUrl: org?.twitter_url,
    organizationFacebookUrl: org?.facebook_url,
    organizationBlogUrl: org?.blog_url,
    organizationCrunchbaseUrl: org?.crunchbase_url,
    organizationAngellistUrl: org?.angellist_url,
    organizationFoundedYear: org?.founded_year,
    organizationPrimaryPhone: org?.primary_phone?.number,
    organizationPubliclyTradedSymbol: org?.publicly_traded_symbol,
    organizationPubliclyTradedExchange: org?.publicly_traded_exchange,
    organizationAnnualRevenuePrinted: org?.annual_revenue_printed,
    organizationTotalFunding: org?.total_funding?.toString(),
    organizationTotalFundingPrinted: org?.total_funding_printed,
    organizationLatestFundingRoundDate: org?.latest_funding_round_date,
    organizationLatestFundingStage: org?.latest_funding_stage,
    organizationFundingEvents: org?.funding_events,
    organizationCity: org?.city,
    organizationState: org?.state,
    organizationCountry: org?.country,
    organizationStreetAddress: org?.street_address,
    organizationPostalCode: org?.postal_code,
    organizationTechnologyNames: org?.technology_names,
    organizationCurrentTechnologies: org?.current_technologies,
    organizationKeywords: org?.keywords,
    organizationIndustries: org?.industries,
    organizationSecondaryIndustries: org?.secondary_industries,
    organizationNumSuborganizations: org?.num_suborganizations,
    organizationRetailLocationCount: org?.retail_location_count,
    organizationAlexaRanking: org?.alexa_ranking,
  };
}

/**
 * Extract person/org DB values from an Apollo API person.
 * Returns only the data columns (caller adds orgId, runId, etc.).
 */
export function toEnrichmentDbValues(person: ApolloPerson) {
  const org = person.organization;
  return {
    apolloPersonId: person.id,
    firstName: person.first_name,
    lastName: person.last_name,
    email: person.email,
    emailStatus: person.email_status,
    title: person.title,
    linkedinUrl: person.linkedin_url,
    photoUrl: person.photo_url,
    headline: person.headline,
    city: person.city,
    state: person.state,
    country: person.country,
    seniority: person.seniority,
    departments: person.departments,
    subdepartments: person.subdepartments,
    functions: person.functions,
    twitterUrl: person.twitter_url,
    githubUrl: person.github_url,
    facebookUrl: person.facebook_url,
    employmentHistory: person.employment_history,
    // Organization
    organizationName: org?.name,
    organizationDomain: org?.primary_domain,
    organizationIndustry: org?.industry,
    organizationSize: org?.estimated_num_employees?.toString(),
    organizationRevenueUsd: org?.annual_revenue?.toString(),
    organizationWebsiteUrl: org?.website_url,
    organizationLogoUrl: org?.logo_url,
    organizationShortDescription: org?.short_description,
    organizationSeoDescription: org?.seo_description,
    organizationLinkedinUrl: org?.linkedin_url,
    organizationTwitterUrl: org?.twitter_url,
    organizationFacebookUrl: org?.facebook_url,
    organizationBlogUrl: org?.blog_url,
    organizationCrunchbaseUrl: org?.crunchbase_url,
    organizationAngellistUrl: org?.angellist_url,
    organizationFoundedYear: org?.founded_year,
    organizationPrimaryPhone: org?.primary_phone?.number,
    organizationPubliclyTradedSymbol: org?.publicly_traded_symbol,
    organizationPubliclyTradedExchange: org?.publicly_traded_exchange,
    organizationAnnualRevenuePrinted: org?.annual_revenue_printed,
    organizationTotalFunding: org?.total_funding?.toString(),
    organizationTotalFundingPrinted: org?.total_funding_printed,
    organizationLatestFundingRoundDate: org?.latest_funding_round_date,
    organizationLatestFundingStage: org?.latest_funding_stage,
    organizationFundingEvents: org?.funding_events,
    organizationCity: org?.city,
    organizationState: org?.state,
    organizationCountry: org?.country,
    organizationStreetAddress: org?.street_address,
    organizationPostalCode: org?.postal_code,
    organizationTechnologyNames: org?.technology_names,
    organizationCurrentTechnologies: org?.current_technologies,
    organizationKeywords: org?.keywords,
    organizationIndustries: org?.industries,
    organizationSecondaryIndustries: org?.secondary_industries,
    organizationNumSuborganizations: org?.num_suborganizations,
    organizationRetailLocationCount: org?.retail_location_count,
    organizationAlexaRanking: org?.alexa_ranking,
    responseRaw: person,
  };
}

/**
 * Transform a cached DB enrichment row back to the API response format.
 * Used when returning a cache hit from POST /enrich.
 */
export function transformCachedEnrichment(
  apolloPersonId: string,
  row: ApolloPeopleEnrichment
) {
  return {
    id: apolloPersonId,
    firstName: row.firstName,
    lastName: row.lastName,
    email: row.email,
    emailStatus: row.emailStatus,
    title: row.title,
    linkedinUrl: row.linkedinUrl,
    photoUrl: row.photoUrl,
    headline: row.headline,
    city: row.city,
    state: row.state,
    country: row.country,
    seniority: row.seniority,
    departments: row.departments,
    subdepartments: row.subdepartments,
    functions: row.functions,
    twitterUrl: row.twitterUrl,
    githubUrl: row.githubUrl,
    facebookUrl: row.facebookUrl,
    employmentHistory: row.employmentHistory,
    organizationName: row.organizationName,
    organizationDomain: row.organizationDomain,
    organizationIndustry: row.organizationIndustry,
    organizationSize: row.organizationSize,
    organizationRevenueUsd: row.organizationRevenueUsd,
    organizationWebsiteUrl: row.organizationWebsiteUrl,
    organizationLogoUrl: row.organizationLogoUrl,
    organizationShortDescription: row.organizationShortDescription,
    organizationSeoDescription: row.organizationSeoDescription,
    organizationLinkedinUrl: row.organizationLinkedinUrl,
    organizationTwitterUrl: row.organizationTwitterUrl,
    organizationFacebookUrl: row.organizationFacebookUrl,
    organizationBlogUrl: row.organizationBlogUrl,
    organizationCrunchbaseUrl: row.organizationCrunchbaseUrl,
    organizationAngellistUrl: row.organizationAngellistUrl,
    organizationFoundedYear: row.organizationFoundedYear,
    organizationPrimaryPhone: row.organizationPrimaryPhone,
    organizationPubliclyTradedSymbol: row.organizationPubliclyTradedSymbol,
    organizationPubliclyTradedExchange: row.organizationPubliclyTradedExchange,
    organizationAnnualRevenuePrinted: row.organizationAnnualRevenuePrinted,
    organizationTotalFunding: row.organizationTotalFunding,
    organizationTotalFundingPrinted: row.organizationTotalFundingPrinted,
    organizationLatestFundingRoundDate: row.organizationLatestFundingRoundDate,
    organizationLatestFundingStage: row.organizationLatestFundingStage,
    organizationFundingEvents: row.organizationFundingEvents,
    organizationCity: row.organizationCity,
    organizationState: row.organizationState,
    organizationCountry: row.organizationCountry,
    organizationStreetAddress: row.organizationStreetAddress,
    organizationPostalCode: row.organizationPostalCode,
    organizationTechnologyNames: row.organizationTechnologyNames,
    organizationCurrentTechnologies: row.organizationCurrentTechnologies,
    organizationKeywords: row.organizationKeywords,
    organizationIndustries: row.organizationIndustries,
    organizationSecondaryIndustries: row.organizationSecondaryIndustries,
    organizationNumSuborganizations: row.organizationNumSuborganizations,
    organizationRetailLocationCount: row.organizationRetailLocationCount,
    organizationAlexaRanking: row.organizationAlexaRanking,
  };
}
